### PR TITLE
Adds json with all meetup ids

### PR DESCRIPTION
**Pull request by hidnasio**
Adds a json with all the ids of the meetups to be used in the new website 

https://github.com/jubar/ember-montevideo-app/issues/11

### CODE REVIEW

**Comment by san650** [comment]
Just an FYI, @xymbol is working on a script that generates the meetup notes directly from meetup.com. Maybe we could update that script to update this JSON file. What do you think? It can be a follow up PR.

See https://github.com/ember-montevideo/meetups/pull/20

**Comment by xymbol** [comment]
@san650 @hidnasio I can add this, the script already gets event ids on start to query per-event attendance.

- Should we match event dates to months?
- What if we had more than one event in a month?

I also wanted to look into how to match Meetup to Twitter accounts. Ideas?

**Comment by hidnasio** [comment]
@xymbol right now the website supports only 1 event per month. I guess this will be a problem in the future but for now let's assume that.

About the twitter accounts, I don't think there is an easy way to do that.

**Comment by xymbol** [comment]
>About the twitter accounts, I don't think there is an easy way to do that.

@hidnasio Keep a map around, maybe?

**Pull request merged**
