### PR TITLE
WIP: Agrega notas que faltan

### PR DESCRIPTION
**Pull request by xymbol**

### CODE REVIEW

**Comment by san650** [comment]
👏 👏 👏

**Comment by san650** [comment]
@xymbol do you think we can merge this AS IS? We could fill the notes later for the ones we have info.

**Comment by xymbol** [comment]
@san650 Probably not, I **do** have most materials, including Keynote slides and even a few pics. Will ask for reviews when it's done.

**Comment by san650** [comment]
@xymbol let me know if you need help.

**Pull request merged**
